---
default_install_hook_types:
  - pre-commit

repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: python -m mypy
        language: system
        'types_or': [ python, pyi ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.9"
    hooks:
      - id: ruff
        args: [ --fix, --unsafe-fixes ]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: ^.+(\.md)$
