---
default_install_hook_types:
  - pre-commit

repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: "v0.5.1"
    hooks:
      - id: go-fmt
      # - id: go-vet
      # - id: go-imports
      # - id: golangci-lint
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: ^.+(\.md)$
