[tool.poetry]
name = "FeedForBot"
version = "0.1.0"
description = "Forward links from RSS/Atom feeds to messengers"
authors = ["Aleksandr Shpak <shpaker@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/shpaker/feedforbot"
repository = "https://github.com/shpaker/feedforbot"

[tool.poetry.scripts]
feedforbot = 'feedforbot.cli:main'

[tool.poetry.dependencies]
python = "^3.10"
httpx = "^0.23.1"
feedparser = "^6.0.10"
pydantic = "^1.10.2"
click = "^8.1.3"
aiocron = "^1.8"
beautifulsoup4 = "^4.11.1"
aiofiles = "^22.1.0"
pyyaml = "^6.0"
jinja2 = "^3.1.2"
orjson = "^3.8.2"
sentry-sdk = "^1.11.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"
black = "^22.10.0"
isort = "^5.10.1"
mypy = "^0.991"
pylint = "^2.15.6"
flake8 = "^5.0.4"
pytest = "^7.2.0"
pytest-asyncio = "^0.20.2"
freezegun = "^1.2.2"
types-aiofiles = "^22.1.0.4"
types-pyyaml = "^6.0.12.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

line-length = 79
verbose = 1
color = true
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.mypy_cache
    | \.pytest_cache
    | \.venv
  )/
)
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 79
src_paths = ["feedforbot", "tests"]
skip = [".mypy_cache", ".pytest_cache", "venv"]

[tool.pylint.messages_control]
disable = "missing-docstring, no-member, too-few-public-methods, logging-fstring-interpolation"

[tool.pylint.format]
max-line-length = "79"
indent-string = "    "
good-names = "fh, id, to"

[tool.pylint.master]
ignore = "venv,tests"
indent-string = "    "
extension-pkg-whitelist = "pydantic"

[tool.black]
line-length = 79
verbose = 1
color = true
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.mypy_cache
    | \.pytest_cache
    | \.venv
  )/
)
'''
