---
cache:
  type: 'files'
schedulers:
  - listener:
      type: 'rss'
      params:
        url: 'https://habr.com/ru/rss/articles/?fl=ru'
    transport:
      type: 'telegram_bot'
      params:
        token: '{{ feedforbot_token }}'
        to: '@tmfeed'
        template: |-
          <b>{{ '{{' }} TITLE {{ '}}' }}</b> #habr
          {{ '{{' }} ID {{ '}}' }}
          <b>Tags</b>: {{ '{%' }} for category in CATEGORIES {{ '%}' }}{{ '{{' }} category {{ '}}' }}{{ '{{' }} ", " if not loop.last else "" {{ '}}' }}{{ '{%' }} endfor {{ '%}' }}
          <b>Author</b>: <a href="https://habr.com/users/{{ '{{' }} AUTHORS[0] {{ '}}' }}">{{ '{{' }} AUTHORS[0] {{ '}}' }}</a>
  - listener:
      type: 'rss'
      params:
        url: 'https://habr.com/ru/rss/news/?fl=ru'
    transport:
      type: 'telegram_bot'
      params:
        token: '{{ feedforbot_token }}'
        to: '@tmfeed'
        template: |-
          <b>{{ '{{' }} TITLE {{ '}}' }}</b> #habr
          {{ '{{' }} ID {{ '}}' }}
          <b>Tags</b>: {{ '{%' }} for category in CATEGORIES {{ '%}' }}{{ '{{' }} category {{ '}}' }}{{ '{{' }} ", " if not loop.last else "" {{ '}}' }}{{ '{%' }} endfor {{ '%}' }}
  - listener:
      type: 'rss'
      params:
        url: 'http://www.opennet.ru/opennews/opennews_all.rss'
    transport:
      type: 'telegram_bot'
      params:
        token: '{{ feedforbot_token }}'
        to: '@tmfeed'
        disable_web_page_preview: yes
        template: |-
          <b>{{ '{{' }} TITLE {{ '}}' }}</b> #opennet
          {{ '{{' }} URL {{ '}}' }}

          {{ '{{' }} TEXT {{ '}}' }}
