---
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY_HOST: ghcr.io
    steps:
      - uses: actions/checkout@v4
      - name: Extract version
        shell: bash
        run: |
          echo "name=$(echo ${GITHUB_REPOSITORY#*/})" >> "$GITHUB_OUTPUT"
          echo "ver=$(echo ${GITHUB_REF#refs/*/})" >> "$GITHUB_OUTPUT"
          echo "minor_ver=$(TMP_VAR=${GITHUB_REF#refs/*/}; echo ${TMP_VAR%.*})" >> "$GITHUB_OUTPUT"
          echo "major_ver=$(TMP_VAR=${GITHUB_REF#refs/*/}; echo ${TMP_VAR%.*.*})" >> "$GITHUB_OUTPUT"
        id: extract_name_and_version
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: sed -i 's/0.1.0/'"${{ steps.extract_name_and_version.outputs.ver }}"'/' pyproject.toml
      - run: sed -i 's/0.1.0/'"${{ steps.extract_name_and_version.outputs.ver }}"'/' feedforbot/__version__.py
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            "${{ env.REGISTRY_HOST }}/${{ github.repository }}:latest"
            "${{ env.REGISTRY_HOST }}/${{ github.repository }}:${{ steps.extract_name_and_version.outputs.major_ver }}"
            "${{ env.REGISTRY_HOST }}/${{ github.repository }}:${{ steps.extract_name_and_version.outputs.minor_ver }}"
            "${{ env.REGISTRY_HOST }}/${{ github.repository }}:${{ steps.extract_name_and_version.outputs.ver }}"
            "${{ github.repository }}:latest"
            "${{ github.repository }}:${{ steps.extract_name_and_version.outputs.major_ver }}"
            "${{ github.repository }}:${{ steps.extract_name_and_version.outputs.minor_ver }}"
            "${{ github.repository }}:${{ steps.extract_name_and_version.outputs.ver }}"
          labels: |
            org.opencontainers.image.title=feedforbot
            org.opencontainers.image.description=Forward links from RSS/Atom feeds to messengers
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
            org.opencontainers.image.authors=Aleksandr Shpak <shpaker@gmail.com>
            org.opencontainers.image.version=${{ steps.extract_name_and_version.outputs.ver }}
            org.opencontainers.image.created=${{ github.event.release.created_at }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=MIT
          provenance: false
          cache-from: type=registry,ref=${{ env.REGISTRY_HOST }}/${{ github.repository }}:${{ steps.extract_name_and_version.outputs.minor_ver }}
          cache-to: type=inline
