name: Lint

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PYTHON_VERSION:
          - "3.10"
          - "3.11"
          - "3.12"
        JUST_JOB:
          - "linters"
          - "tests"
    steps:
      - uses: extractions/setup-just@v1
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
      - uses: actions/checkout@v3
      - run: |
          python -m pip install poetry~=1.7.0
          poetry install --no-root --no-ansi --with ${{ matrix.JUST_JOB }}
      - run: just ${{ matrix.JUST_JOB }}
