name: Lint

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v3
      - run: |
          python -m pip install poetry==1.2.2
          poetry install -vvv --no-root
      - run: poetry run pre-commit install-hooks
      - run: poetry run pre-commit run flake8 --all-files --show-diff-on-failure
      - run: poetry run pre-commit run pylint --all-files --show-diff-on-failure
      - run: poetry run pre-commit run mypy --all-files --show-diff-on-failure
