---
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v3
      - name: Extract branch name
        shell: bash
        run: |
          echo "##[set-output name=name;]$(echo ${GITHUB_REPOSITORY#*/})"
          echo "##[set-output name=ver;]$(echo ${GITHUB_REF#refs/*/})"
          echo "##[set-output name=minor_ver;]$(TMP_VAR=${GITHUB_REF#refs/*/}; echo ${TMP_VAR%.*})"
          echo "##[set-output name=major_ver;]$(TMP_VAR=${GITHUB_REF#refs/*/}; echo ${TMP_VAR%.*.*})"
          echo "##[set-output name=sha;]$(git rev-parse --short "$GITHUB_SHA")"
        id: extract_name_and_version
      - run: sed -i 's/0.1.0/'"${{ steps.extract_name_and_version.outputs.ver }}"'/' pyproject.toml
      - run: head -n 10 pyproject.toml
      - run: sed -i 's/0.1.0/'"${{ steps.extract_name_and_version.outputs.ver }}"'/' feedforbot/version.py
      - run: python -m pip install poetry==1.2.2
      - run: poetry build
      - run: poetry config http-basic.pypi ${{ secrets.PYPI_LOGIN }} ${{ secrets.PYPI_PASS }}
      - run: poetry publish
