---
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Extract version
        shell: bash
        run: |
          echo "ver=$(echo ${GITHUB_REF#refs/*/})" >> "$GITHUB_OUTPUT"
        id: extract_version
      - run: sed -i 's/0.1.0/'"${{ steps.extract_version.outputs.ver }}"'/' pyproject.toml
      - run: sed -i 's/0.1.0/'"${{ steps.extract_version.outputs.ver }}"'/' feedforbot/__version__.py
      - run: uv build
      - run: uv publish
        env:
          UV_PUBLISH_USERNAME: ${{ secrets.PYPI_LOGIN }}
          UV_PUBLISH_PASSWORD: ${{ secrets.PYPI_PASS }}
