name: Test

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      SOURCES_DIR: sources
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/setup-python@v4
        with:
            python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v3
      - run: |
          python -m pip install poetry==1.2.2
          poetry install -vvv --no-root
      - run: poetry run pytest -vv
